# dotfiles/zsh/zshrc
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"

plugins=(
  git
  z
  docker
  sudo
  history
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# 自作設定
#source ~/dotfiles/zsh/aliases.zsh
#source ~/dotfiles/zsh/keybind.zsh
